In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [4]:
#assume user input
#pclass gendee  age embarked sibsp parch fare

user_input = np.array([2,'male',31.0,0,7.25,'S'],dtype=object).reshape(1,6)

In [5]:
user_input

array([[2, 'male', 31.0, 0, 7.25, 'S']], dtype=object)

In [6]:
user_input_sex =ohe_sex.transform(user_input[:,1].reshape(1,1))

C:\Users\bhavy\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [25]:
user_input_sex

array([[0., 1.]])

In [8]:
user_input_embarked = ohe_embarked.transform(user_input[:,-1].reshape(1,1))

C:\Users\bhavy\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [27]:
user_input_embarked

array([[0., 0., 1., 0.]])

In [14]:
user_input_age = user_input[:,2].reshape(1,1)

In [15]:
user_input_age

array([[31.0]], dtype=object)

In [31]:
user_input_transformed = np.concatenate(
    (
        user_input[:, [0, 3, 4, 5]],   # Pclass, SibSp, Parch, Fare
        user_input_age,
        user_input_sex,
        user_input_embarked
    ),
    axis=1
)

In [32]:
user_input_transformed.shape

(1, 11)